# Site settings
title: iemxblog
email: iemxblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Développement, logiciels libres, électronique, usinage, CNC, do-it-yourself, arduino, raspberry pi, et diverses autres choses.
  Des projets que je réalise, des astuces, des liens, des bouts de code...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iemxblog.github.io" # the base hostname & protocol for your site
twitter_username: iemxblog
github_username: iemxblog

# Build settings
markdown: kramdown
